---
title: "Assignment2"
author: "John Shen","Elaina Sinclair","Zihao Liu"
date: "2/3/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1

This statement is problematic because if the correlation does not reflect true cause, it would be a spurious correlation - and treating it like a causal effect may not lead to improvement in health in the future. 

## Question 2

First number = E (exposure), second number = A (adherence)
risk difference: $$E(Y^{11} - Y^{01})$$
risk ratio: $$\frac{E(Y^{11})}{E(Y^{01})}$$
Odds ratio: $$\frac{OddsE(Y^{11})}{OddsE(Y^{01})}$$

## Question 3

Difference between the risk if the entire treated population would receive four consecutive days (days 1-4) of treatment versus the risk if the entire treated population would received only three consecutive days of treatment (days 1-3).

## Question 4

$$\frac{E(Y^{d_{4}=1})}{E(Y^{d_{4}=0})}$$

## Question 5



## Question 6

Risk difference: If all smokers quit smoking they would have a 12.9% reduction in risk of high blood pressure (12.9 out of 100 fewer former smokers would not develop high blood pressure)
Risk  Ratio: If all smokers quit smoking, their risk of high blood pressure would be 53% of the risk if they had continued to smoke.
Odds Ratio: If all smokers quit smoking, their odds of high blood pressure would be 45% of the odds if the had continued to smoke.

## Question 7

The average treatment effect would be more relevant for the relation between quitting smoking and high blood pressure because we are interested in how quitting smoking would affect all smokers. If we only look at effect of quitting smoking among those who were observed to have quit smoking (i.e. effect of treatment on the treated), there may be other confounding factors (e.g. those who quit may tend to engage in more healthier lifestyle changes than those who didn't) that would affect their blood pressure and alter effect of quitting smoking on this subgroup. 

## Question 8

Participant who would still go through second-hand smoking even after he or she quit smoking already, thus the potensial outcome would be affected y the exposure status of other individual.

## Question 9

The authors are assuming consistency and no interference (SUTVA) because these two assumptions are what allow us to equate the observed outcomes conditioned on the treatment to the potential outcomes conditioned on the treatment.

## Question 10

