---
title: "EPI560 HW2"
output: html_document
---

Question 1: Consider the following statement from Mayer-Schonberger and Cukier (2013) “Big Data: A Revolution That Will Transform How we Live, Work, and Think”, page 14:

“Correlations may not tell us precisely why something is happening, but they alert us that it is happening. And in many situations this is good enough. If millions of electronic medical records reveal that cancer sufferers who take a certain combination of aspirin and orange juice see their disease go into remission,then the exact cause for the improvement in health may be less important than the fact that they lived. . . . we can let the data speak for itself.”
Other than the fact that they mix up singular and plural by stating that we should let the “data” (plural) speak for “itself” (singular) :-), describe in one paragraph (no longer than one half page) why this statement is problematic. Provide an example illustrating how their interpretation of the scenario may be erroneous.


This statement is problematic because if the correlation does not reflect true cause, it would be a spurious correlation - and treating it like a causal effect may not lead to improvement in health in the future. 


Question 2) In randomized controlled trial settings, researchers are often interested in estimating per protocol effects. Consider a simple scenario with a randomization indicator R, with R = 0 denoting “assigned to placebo” and R = 1 denoting “assigned to treated”, an adherence indicator A, with A = 0 denoting “did not adhere” and A = 1 denoting “adhered by taking treatment on the day randomized”, and an outcome variable Y , with Y = 1 denoting “event”, and Y = 0 denoting “no event”. Can you write the per protocol effect, defined as being assigned to treatment and adhering relative to being assigned to placebo and adhering, using potential outcomes notation? Write these effects on the risk difference, risk ratio, and odds ratio scales.


First number = E (exposure), second number = A (adherence)
risk difference: $$E(Y^{11} - Y^{01})$$
risk ratio: $$\frac{E(Y^{11})}{E(Y^{01})}$$
Odds ratio: $$\frac{OddsE(Y^{11})}{OddsE(Y^{01})}$$


Question 3) Suppose we conduct a study of the the effect of 6 mg Dexamethasone daily versus placebo on a measure of lung function one week after admission to the hospital due to respiratory symptoms resulting from infection with SARS-CoV-2. Suppose we let Y denote lung function at the end of seven days, and Dj denote Dexamethasone treatment on day j of follow-up (e.g., Dj = 1 denotes treated with Dexamethasone on day j; Dj = 0 denotes not treated with Dexamethasone on day j). Please describe, in words, the effect that the following contrast of potential outcomes captures:



Difference between the risk if the entire treated population would receive four consecutive days (days 1-4) of treatment versus the risk if the entire treated population would received only three consecutive days of treatment (days 1-3).



Question 4) Please re-write the right-hand side of the equation in Question 3 more compactly (instead of writing out the exposure value on each of the seven days).


$$\frac{E(Y^{d_{4}=1})}{E(Y^{d_{4}=0})}$$


Question 5: Please complete the Table under SUTVA:




Question 6: Suppose the average treatment effect on the risk difference, risk ratio, and odds ratio scales for the relation between quitting smoking and high blood pressure is -0.129, 0.53, and 0.45, respectively. Suppose further that the identification assumptions required for interpreting these associations as causal effects holds.
Please interpret these effect measures.



Question 7: For the example of the relation between quitting smoking and high blood pressure, do you think the average treatment effect or the effect of treatment on the treated is more relevant? Explain why or why not.



Question 8: Again, for the example of the relation between quitting smoking and high blood pressure, can you describe a scenario where we may collect some data and where the no interference assumption would be violated?




Question 9: Consider the following statement from a paper by Athey et al (2020)[https://arxiv.org/pdf/1909.02210.pdf], page 14: In the setting of interest we have data on an outcome Yi, a set of pretreatment variables Xi and a binary treatment Wi ∈ {0,1}. We postulate that there exists for each unit in the population two potential outcomes Yi(0) and Yi(1), with the observed outcome equal to corresponding to the potential outcome for the treatment received, Yi = Yi(Wi). What assumption(s) are the authors relying on when they say “We postulate that there exists . . . ”? Why?




Question 10: Consider the exchangeability assumption. Why is the word “exchangeable” used to describe this concept? What, precisely, is being exchanged?




Question 11: Consider a regression model with an exposure and 11 confounders, for a total of 12 variables:

E(Y |X,C) = β0 + β1X + β2C1 + ... + β12C11

What is the total number of possible interactions in this model? What are the total number of 2-wayinteractions? Show your reasoning.



Question 12: Suppose you had superpowers and were able to measure potential outcomes. Suppose you used these measures to fit a model that regresses the exposure A against all measured confounders C (i.e., propensity score model), and that there was no measured confounding, selection bias, and information bias (i.e., exchageability was met). If you included the potential outcomes in the regression model:
logit{P(A = 1 |C,Y a)}= β0 + β1C1 + ... + βpCp + θY a
Can you determine from this information alone what the value of θ is if exchangeability holds? Can you determine what the value of θ is if exchangeability doesn’t hold?




Question 13: Install the AIPW package from CRAN and load the library. Then load the “eager_sim_obs” dataset using the data("eager_sim_obs") command. Using these data, generate (i) a propensity score over lap plot, (ii) a list of the five largest and smallest propensity scores, and (iii) the summary distribution of the stabilized inverse probability weights using a propensity score model that adjusts for eligibility, loss_num, age, time_try_pregnant, BMI, and meanAP. Is positivity violated in these data? Why or why not?




Question 14: Consider a two-arm placebo controlled randomized trial with four mutually exclusive strata labeled S = 1,S = 2,S = 3 and S = 4. Suppose that the treatment was assigned to: 20% of individuals in stratum S = 1; 30% of individuals in stratum S = 2; 15% of individuals in stratum S = 3; and 10% of individuals in stratum S = 4. Can you determine all of the propensity score values in the sample of individuals in the trial?




(Bonus?) Question 15 Using the information provided in Question 14, please write a logistic regression equation that the defines the propensity score for this randomized trial. What are the parameter values in this logistic regression model?
